fint:
  endpoints:
    drosjeloyve:
    drosjeloyve-mappe-id:
    dokumentfil:
    attachment:
    application:
    evidence:

scheduling:
  initial-delay: 10000
  fixed-delay: 360000

drosjeloyve:
  organisations:

spring:
  security:
    oauth2:
      client:
        registration:
        provider:
          fint:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus
