scheduling:
  initial-delay: 10000
  fixed-delay: 60000

organisation:
  921693230:
    name: Viken fylkeskommune
    registration: viken
    policy:
    username: username
    password: password

spring:
  security:
    oauth2:
      client:
        registration:
          viken:
            client-id: client-id
            client-secret: client-secret
            authorization-grant-type: password
            scope: fint-client
            provider: fint
        provider:
          fint:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token


