fint:
  endpoints:
    drosjeloyve: https://alpha.felleskomponent.no/arkiv/samferdsel/drosjeloyve
    drosjeloyve-mappe-id: https://alpha.felleskomponent.no/arkiv/samferdsel/drosjeloyve/mappeid/{id}
    dokumentfil: https://alpha.felleskomponent.no/arkiv/noark/dokumentfil
    attachment: http://altinn-downloadqueue-service:8080/applications/{id}
    application: http://altinn-downloadqueue-service:8080/attachments/{id}
    evidence: http://altinn-ebevis-service:8080/evidence/{id}

scheduling:
  initial-delay: 10000
  fixed-delay: 360000

drosjeloyve:
  organisations:
    921693230:
      name: Viken fylkeskommune
      registration: viken
      deviation-policy:
      skjermingshjemmel:
      tilgangsrestriksjon:
      username: username
      password: password

spring:
  security:
    oauth2:
      client:
        registration:
          viken:
            client-id: client-id
            client-secret: client-secret
            authorization-grant-type: password
            scope: fint-client
            provider: fint
        provider:
          fint:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token


