fint:
  endpoints:
    drosjeloyve:
    drosjeloyve-mappe-id:
    drosjeloyve-system-id:
    dokumentfil:
    dokumentfil-system-id:
    attachment:
    application:
    evidence:

scheduling:
  initial-delay: 10000
  fixed-delay: 360000

organisations:
  921693230:
    name: Viken fylkeskommune
    registration: viken
    deviation-policy:
    skjermingshjemmel:
    tilgangsrestriksjon:
    username: username
    password: password

spring:
  security:
    oauth2:
      client:
        registration:
          viken:
            client-id: client-id
            client-secret: client-secret
            authorization-grant-type: password
            scope: fint-client
            provider: fint
        provider:
          fint:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token


