fint:
  endpoints:
    drosjeloyve: https://alpha.felleskomponent.no/arkiv/samferdsel/drosjeloyve
    drosjeloyve-mappe-id: https://alpha.felleskomponent.no/arkiv/samferdsel/drosjeloyve/mappeid/{id}
    drosjeloyve-system-id: https://alpha.felleskomponent.no/arkiv/samferdsel/drosjeloyve/systemid/{id}
    dokumentfil: https://alpha.felleskomponent.no/arkiv/noark/dokumentfil
    dokumentfil-system-id: https://alpha.felleskomponent.no/arkiv/noark/dokumentfil/systemid/{id}
    attachment:
    application:
    evidence:

scheduling:
  initial-delay: 10000
  fixed-delay: 360000

organisations:
  921693230:
    name: Viken fylkeskommune
    registration: viken
    deviation-policy:
    username: username
    password: password

spring:
  security:
    oauth2:
      client:
        registration:
          viken:
            client-id: client-id
            client-secret: client-secret
            authorization-grant-type: password
            scope: fint-client
            provider: fint
        provider:
          fint:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token


