apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - onepassword.yaml
  - service.yaml
  - fint-client-afk-no.yaml
  - fint-client-bfk-no.yaml
  - fint-client-ofk-no.yaml
  - fint-client-ffk-no.yaml
  - fint-client-tromsfylke-no.yaml
  - fint-client-telemarkfylke-no.yaml
  - fint-client-vestfoldfylke-no.yaml

patches:

  - target:
      kind: Deployment
      name: drosjeloyve-service
    path: deployment.yaml
