apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - onepassword.yaml
  - service.yaml
  - fint-client-afk.yaml
  - fint-client-bfk.yaml
  - fint-client-ofk.yaml
  - fint-client-ffk.yaml
  - fint-client-tromsfylke.yaml
  - fint-client-telemarkfylke.yaml
  - fint-client-vestfoldfylke.yaml

patches:

  - target:
      kind: Deployment
      name: drosjeloyve-service
    path: deployment.yaml
