package no.fint.drosjeloyve.model;

public enum AltinnApplicationStatus {
    NEW, REQUESTOR_MISSING, CONSENTS_INVALID_SUBJECT, CONSENTS_REJECTED_OR_EXPIRED, CONSENTS_REQUESTED, CONSENTS_ACCEPTED, ARCHIVED, PURGED
}
