apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - onepassword.yaml
  - service.yaml
#  - fint-adapter.yaml

patches:

  - target:
      kind: Deployment
      name: drosjeloyve-service
    path: deployment.yaml
