apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - onepassword.yaml
  - service.yaml
  - fint-client-agderfk-no.yaml
  - fint-client-bym-oslo-kommune-no.yaml
  - fint-client-mrfylke-no.yaml
  - fint-client-rogfk-no.yaml
  - fint-client-trondelagfylke-no.yaml

patches:

  - target:
      kind: Deployment
      name: drosjeloyve-service
    path: deployment.yaml
